# Generated by Django 3.2.6 on 2021-08-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_alter_meetup_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='orgranizer_email',
            new_name='organizer_email',
        ),
    ]
